modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sealdice2mc"
version = "${version}"
displayName = "sealdice2MC"
authors = "DontPlay"
description = '''
A mod let you Connect SealDice to Minecraft
'''
#logoFile = ""

[[dependencies.sealdice2mc]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sealdice2mc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sealdice2mc]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
