plugins {
    id 'dev.architectury.loom' version '1.11-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.gradleup.shadow' version '8.3.6' apply false
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'

    base {
        archivesName = "$rootProject.archives_name-$project.name"
    }

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.officialMojangMappings()
    }

    java {
        // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
        // if it is present.
        // If you remove this line, sources will not be generated.
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }
}

publishMods {
    def env = System.getenv()
    def publishType = env.RELEASE_TYPE ?: "release"
    def fabricStr = "fabric"
    def forgeStr = "neoforge"
    def versionBase = rootProject.mod_version + "-"
    def displayNameBase = rootProject.archives_name + " "

    type = publishType == "release" ? STABLE : (publishType == "beta" ? BETA : ALPHA)
    changelog = env.CHANGELOG_TEXT ?: "fix some bugs"

    def cfOptions = curseforgeOptions {
        accessToken = env.CURSEFORGE_TOKEN
        projectId = "1503025"
        minecraftVersions.add(rootProject.minecraft_version)
    }
 
    // Modrinth options used by both Fabric and Forge
    def mrOptions = modrinthOptions {
        accessToken = env.MODRINTH_TOKEN
        projectId = "8ScQVxiU"
        minecraftVersions.add(rootProject.minecraft_version)
    }

    curseforge("curseforgeFabric") {
        from cfOptions
        version = versionBase + fabricStr
        displayName = displayNameBase + fabricStr + rootProject.mod_version
        file project(":"+fabricStr).tasks.remapJar.archiveFile
        modLoaders.add(fabricStr)
        requires("fabric-api", "architectury-api")
    }
 
    curseforge("curseforgeForge") {
        from cfOptions
        version = versionBase + forgeStr
        displayName = displayNameBase + forgeStr + rootProject.mod_version
        file project(":"+forgeStr).tasks.remapJar.archiveFile
        modLoaders.add(forgeStr)
        requires("architectury-api")
    }
 
    modrinth("modrinthFabric") {
        from mrOptions
        version = versionBase + fabricStr
        displayName = displayNameBase + fabricStr + rootProject.mod_version
        file project(":"+fabricStr).tasks.remapJar.archiveFile
        modLoaders.add(fabricStr)
        requires("fabric-api", "architectury-api")
    }
 
    modrinth("modrinthForge") {
        from mrOptions
        version = versionBase + forgeStr
        displayName = displayNameBase + forgeStr + rootProject.mod_version
        file project(":"+forgeStr).tasks.remapJar.archiveFile
        modLoaders.add(forgeStr)
        requires("architectury-api")
    }
}